language: c

os:
- linux
- osx

compiler:
  - gcc
  - clang

before_install: ./scripts/travis-before-install.sh

#install: sudo apt-get install libsnappy-dev zlib1g-dev
#install: sudo apt-get install liblz4-dev libsnappy-dev zlib1g-dev

before_script:
  - mkdir build_release
  - cd build_release
  - build_release_folder=`pwd`
  - cmake ..

script:
  - cd ${build_release_folder}
  - cmake --build ../build_release --config Release
  - ctest
