language: c
compiler:
  - gcc
  - clang
install: sudo apt-get install libsnappy-dev zlib1g-dev libhdf5-serial-dev
#install: sudo apt-get install liblz4-dev libsnappy-dev zlib1g-dev libhdf5-dev
before_script:
  - mkdir build
  - cd build
  - cmake -DBUILD_HDF5_FILTER=TRUE ..
script: make && make test
