version: 1.0.{build}

image:
  - Visual Studio 2019
  - Visual Studio 2017
  - Visual Studio 2015
  - Visual Studio 2013

configuration:
  - Debug
  - Release

before_build:
  - cmd: cmake -H. -B./build

build_script:
  - cmd: cmake --build ./build

build:
  verbosity: normal

test_script:
  - cmd: cd ./build
  - cmd: ctest -C Debug -VV
