# AppVeyor CI build configuration for c-blosc

# Before cloning the repo, configure git to handle line endings correctly.
init:
    - git config --global core.autocrlf input

build: false

environment:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_USERNAME: "francescalted"
    CONAN_LOGIN_USERNAME: "francescalted"
    CONAN_CHANNEL: "stable"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
    CONAN_UPLOAD: "https://api.bintray.com/conan/blosc/c-blosc"
    CONAN_REMOTES: "https://api.bintray.com/conan/blosc/c-blosc"
    CONAN_VISUAL_RUNTIMES: "MD"
    CONAN_ARCHS: "x86,x86_64"

    matrix:
        - GENERATOR: "Visual Studio 10 2010"
          CONFIG: Release

        - GENERATOR: "Visual Studio 10 2010 Win64"
          CONFIG: Release

        - GENERATOR: "Visual Studio 12 2013"
          CONFIG: Release

        - GENERATOR: "Visual Studio 12 Win64"
          CONFIG: Release

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          GENERATOR: "Visual Studio 14 2015 Win64"
          CONFIG: Release

install:
    - set PATH=%PATH%;%PYTHON%/Scripts/
    - pip.exe install conan --upgrade
    - pip.exe install conan_package_tools
    - conan user # It creates the conan data directory

test_script:
    - appveyor\\winrun.cmd
